name: german_nouns_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you want to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^5.0.0
  firebase_core: ^3.4.1
  firebase_analytics: ^11.3.4
  cloud_firestore: ^5.4.1
  csv: "6.0.0"
  firebase_auth: ^5.3.1
  vibration: ^1.7.4 # Add the vibration package
  shared_preferences: ^2.0.13
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.2.16
  flutter_svg: ^2.0.0
  firebase_storage: ^12.3.5
  random_avatar: ^0.0.8
  material_design_icons_flutter: ^5.0.5955

flutter:
  uses-material-design: true
  assets:
    - assets/ArticleNounPairs.csv
    - assets/galaxy.jpg
    - assets/WelcomeText.txt
    - assets/Adjectives.csv
    - assets/GameOverFrame.svg
    - assets/stars.jpg
    - assets/Stars.csv
    - assets/Nexar2.jpg
    - assets/Aevone.jpg
    - assets/WarpFrame.png
    - assets/ranks/Intern1.svg
    - assets/ranks/Intern2.svg
    - assets/ranks/Intern3.svg
    - assets/ranks/Navigator1.svg
    - assets/ranks/Navigator2.svg
    - assets/ranks/Navigator3.svg
    - assets/ranks/Explorer1.svg
    - assets/ranks/Explorer2.svg
    - assets/ranks/Explorer3.svg
    - assets/ranks/Pilot1.svg
    - assets/ranks/Pilot2.svg
    - assets/ranks/Pilot3.svg
    - assets/ranks/Scholar1.svg
    - assets/ranks/Scholar2.svg
    - assets/ranks/Scholar3.svg
    - assets/ranks/Voyager1.svg
    - assets/ranks/Voyager2.svg
    - assets/ranks/Voyager3.svg
    - assets/ranks/Pioneer1.svg
    - assets/ranks/Pioneer2.svg
    - assets/ranks/Pioneer3.svg
    - assets/ranks/Legend1.svg
    - assets/ranks/Legend2.svg
    - assets/ranks/Legend3.svg
    
