// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example: test
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBp3709qufh1d1PpKXBlD0JOy7eDW2konI',
    appId: '1:932285654519:web:2e6b63e44427cab9a97af2',
    messagingSenderId: '932285654519',
    projectId: 'k48a-955d3',
    authDomain: 'k48a-955d3.firebaseapp.com',
    storageBucket: 'k48a-955d3.firebasestorage.app',
    measurementId: 'G-B3YE0JX7MQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0DNppO54X_cQYl4CRQL866WHNPL3InwI',
    appId: '1:932285654519:android:2c2a6c5e59974560a97af2',
    messagingSenderId: '932285654519',
    projectId: 'k48a-955d3',
    storageBucket: 'k48a-955d3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAx9-vsUM4IM0iDJhKP03bXGvoPscN-jVo',
    appId: '1:932285654519:ios:080ee1ec68f67feba97af2',
    messagingSenderId: '932285654519',
    projectId: 'k48a-955d3',
    storageBucket: 'k48a-955d3.firebasestorage.app',
    iosBundleId: 'com.example.germanNounsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAx9-vsUM4IM0iDJhKP03bXGvoPscN-jVo',
    appId: '1:932285654519:ios:080ee1ec68f67feba97af2',
    messagingSenderId: '932285654519',
    projectId: 'k48a-955d3',
    storageBucket: 'k48a-955d3.firebasestorage.app',
    iosBundleId: 'com.example.germanNounsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBp3709qufh1d1PpKXBlD0JOy7eDW2konI',
    appId: '1:932285654519:web:82d5730159a4d1dea97af2',
    messagingSenderId: '932285654519',
    projectId: 'k48a-955d3',
    authDomain: 'k48a-955d3.firebaseapp.com',
    storageBucket: 'k48a-955d3.firebasestorage.app',
    measurementId: 'G-3J5MK0LZXL',
  );

}