name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Change this to your default branch if it's not 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.27.0'  # Update to a valid Flutter version
        channel: 'stable'
        architecture: 'x64'

    - name: Install dependencies
      run: flutter pub get

    - name: Build web
      run:
        flutter doctor  
        flutter build web

    - name: Deploy to GitHub Pages
      run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git checkout -b gh-pages || git checkout gh-pages
          git pull origin gh-pages --rebase  # Optionally, use --merge or --ff-only
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push origin gh-pages
      env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}