name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Change this to your default branch if it's not 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Ensure the full history is fetched

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.27.0'  # Update to a valid Flutter version
        channel: 'stable'
        architecture: 'x64'

    - name: Install dependencies
      run: flutter pub get

    - name: Build web
      run: 
        flutter doctor
        flutter build web

    - name: Deploy to GitHub Pages
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git remote set-url origin https://${GH_PAT}@github.com/${{ github.repository }}
        git checkout -b gh-pages || git checkout gh-pages
        git merge main --allow-unrelated-histories
        git push origin gh-pages