name: Deploy to GitHub Pages

on:
  push:
    branches:
      - gh-pages  # Change this to your default branch if it's not 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '2.17.0'  # Change this to your desired Flutter version

    - name: Install dependencies
      run: flutter pub get

    - name: Build web
      run: flutter build web --no-tree-shake-icons

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: build/web